version: '3.6'

services:
  node:
    container_name: coder_node_1
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - codernet
  
  db:
    container_name: coder_db_1
    restart: always
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=ezequieldiezemd
      - MONGODB_PASSWORD=Aguanteriver10
      - MONGODB_DATABASE=ecommerce
    networks:
      - codernet


networks:
  codernet:
    driver: "bridge"